# Site settings
title: Danuta Warzecha
email: warzechad@interia.pl
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://danutawarzecha.pl"

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from

navigation:
 - text: Oferta
   url: /oferta.html
 - text: Biuro tłumaczeń
   url: /biuro-tlumaczen.html
 - text: Klienci
   url: /klienci.html
 - text: O mnie
   url: /o-mnie.html
 - text: Kontakt
   url: /kontakt.html
